/**
 * 16×16 map node icons, drawn as palette pixel grids.
 */
import Phaser from 'phaser';
import { drawGrid, makeTexture, outline } from './canvas';

const ICONS: Record<string, string[]> = {
  battle: [
    '................',
    '.ss..........ss.',
    '.sSs........sSs.',
    '..sSs......sSs..',
    '...sSs....sSs...',
    '....sSs..sSs....',
    '.....sSssSs.....',
    '......sSSs......',
    '......sSSs......',
    '.....sSssSs.....',
    '...bbsSs.sSsbb..',
    '...bbbs...sbbb..',
    '..bbb.......bbb.',
    '.bbb.........bbb',
    '.bb...........bb',
    '................',
  ],
  elite: [
    '..r..........r..',
    '..rr........rr..',
    '...rr.RRRR.rr...',
    '....rRRRRRRr....',
    '...RRRRRRRRRR...',
    '..RRwwRRRRwwRR..',
    '..RRwkRRRRkwRR..',
    '..RRRRRRRRRRRR..',
    '..RRRRRddRRRRR..',
    '..RRRRRRRRRRRR..',
    '...RRwRwRwRwR...',
    '...RRwRwRwRwR...',
    '....RRRRRRRR....',
    '.....RRRRRR.....',
    '................',
    '................',
  ],
  shop: [
    '......kkkk......',
    '.....k....k.....',
    '....k......k....',
    '...yyyyyyyyyy...',
    '..yYYYYYYYYYYy..',
    '..yYyyyyyyyyYy..',
    '..yYyRRRRRRyYy..',
    '..yYyRRRRRRyYy..',
    '..yYyRRwRRRyYy..',
    '..yYyRRRRRRyYy..',
    '..yYyRRRRRRyYy..',
    '..yYyyyyyyyyYy..',
    '..yYYYYYYYYYYy..',
    '...yyyyyyyyyy...',
    '......y..y......',
    '.....yy..yy.....',
  ],
  event: [
    '................',
    '.....pppppp.....',
    '....pPPPPPPp....',
    '...pPPwwwwPPp...',
    '...pPw....wPp...',
    '...pPw....wPp...',
    '.........wPPp...',
    '........wPPp....',
    '.......wPPp.....',
    '......wPPp......',
    '......wPPp......',
    '................',
    '......wPPp......',
    '......pPPp......',
    '................',
    '................',
  ],
  rest: [
    '.rrrrrrrrrrrrrr.',
    'rRRRRRRRRRRRRRRr',
    '.rrrrrrrrrrrrrr.',
    '...rR......Rr...',
    '.rrrrrrrrrrrrrr.',
    '...rR......Rr...',
    '...rR......Rr...',
    '...rR..oo..Rr...',
    '...rR.oYYo.Rr...',
    '...rR.oYYo.Rr...',
    '...rR.oyyo.Rr...',
    '...rR..oo..Rr...',
    '...rR.bbbb.Rr...',
    '...rR......Rr...',
    '..rrRr....rRrr..',
    '................',
  ],
  treasure: [
    '................',
    '................',
    '...bbbbbbbbbb...',
    '..bBBBBBBBBBBb..',
    '.bBByyyyyyyyBBb.',
    '.bByYYYYYYYYyBb.',
    '.bbbbbbbbbbbbbb.',
    '.bBBBByyyyBBBBb.',
    '.bBBBByYYyBBBBb.',
    '.bBBBByyyyBBBBb.',
    '.bBBBBBBBBBBBBb.',
    '.bBBBBBBBBBBBBb.',
    '.bbbbbbbbbbbbbb.',
    '................',
    '................',
    '................',
  ],
  boss: [
    '..y....yy....y..',
    '..yy..yYYy..yy..',
    '..yYyyYYYYyyYy..',
    '..yYYYYYYYYYYy..',
    '..yyyyyyyyyyyy..',
    '...wwwwwwwwww...',
    '..wwwwwwwwwwww..',
    '..wwkkwwwwkkww..',
    '..wwkkwwwwkkww..',
    '..wwwwwkkwwwww..',
    '...wwwwwwwwww...',
    '....wkwkwkwk....',
    '....wwwwwwww....',
    '................',
    '................',
    '................',
  ],
};

const COLORS: Record<string, string> = {
  s: '#bcc2d2',
  S: '#f4f6ff',
  b: '#7a3416',
  B: '#c4621e',
  r: '#6e1a2a',
  R: '#e8504a',
  w: '#f4f6ff',
  k: '#120c1c',
  d: '#6e1a2a',
  y: '#c4922a',
  Y: '#f2c94a',
  p: '#3e164e',
  P: '#a650c8',
  o: '#f2953a',
};

export function makeMapIcons(scene: Phaser.Scene): void {
  for (const [k, rows] of Object.entries(ICONS)) {
    makeTexture(scene, `node_${k}`, 18, 18, (c) => {
      drawGrid(c, 1, 1, rows, COLORS);
      outline(c, 0, 0, 18, 18, '#07050b');
    });
  }
}
